version: "3.3"

services:
  app:
    container_name: springboot-postgres
    image: springboot-postgres
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    build: ./utils/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
    volumes:
        - ./docker-entrypoint-initdb.d/10-init.sql
        - postgres_data:/var/lib/postgresql/data/


volumes:
    postgres_data:
