spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://postgresdb:5432/postgres?currentSchema=server
    #url: jdbc:postgresql://localhost:5432/postgres?currentSchema=server
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: /
#    url: /openapi.yaml
#    use-root-path: true
#    url: /v3/api-docs
#    config-url: /v3/api-docs/swagger-config
#    disable-swagger-default-url: true


#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

#  liquibase:
#    enabled: false
#    change-log: classpath:liquibase/changelog.yaml

app:
  jwt:
    secretKey: MySuperSigningSecretKeyForMyServerApplicationMyMegaSigningSecretSecretKeyForMyServerApplication
    tokenExpirationAfterDays: 14
    tokenPrefix: Bearer

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  strategy: default
  exclude:
    - /actuator/**
    - /swagger-ui/**
    - /v3/api-docs/**
    - /api/admin/**
  format:
    style: json
  body:
    max-size: 3000
    filters:
#      body:
      string: nickname,name,email,password
      number: rating,mark,price
  headers:
    enabled: false
  logger:
    active: true


#springdoc:
#  swagger-ui:
#    url: /openapi.yml

#logging:
#  level:
#    org:
#      hibernate:
#        SQL:
#          DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder:
#                TRACE
