databaseChangeLog:
  - changeSet:
      id: 00.001.00/ddl/schema
      author: LyutovaAnastasia
      changes:
        - tagDatabase:
            tag: release/00.001.00

        - sql:
            sql: create schema if not exists server
            endDelimiter: ;

        - rollback:
            sql: drop schema if exists server cascade
            endDelimiter: ;
