openapi: 3.0.3

info:
    title: Reflectoring
    description: "Tutorials on Spring Boot and Java."
    contact:
        email: petros.stergioulas94@gmail.com
    license:
        name: Apache 2.0
    version: 0.0.1-SNAPSHOT
paths:
    /api/section:
        get:
            responses:
                '200':
                    description: OK

